name = "huseyinistan-games"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "none"

[[kv_namespaces]]
binding = "GAMES_KV"
id = "84b31404ac434989925ce123d5e5a6b4"
